# Generated by Django 4.2.5 on 2023-11-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("movies", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SalesModel",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "price",
                    models.FloatField(
                        choices=[(15, "R$15.50"), (25, "R$25.50"), (35, "R$35.50")],
                        default=15.5,
                    ),
                ),
                (
                    "seat",
                    models.IntegerField(
                        choices=[(40, "40 Seats"), (50, "50 Seats"), (60, "60 Seats")],
                        default=40,
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_sales",
                        to="movies.moviesmodel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_sales",
                        to="movies.roomsmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale",
                "verbose_name_plural": "Sales",
                "ordering": ["-created_at"],
            },
        )
    ]
