# Generated by Django 4.2.5 on 2023-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sales", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="salesmodel",
            name="seat",
            field=models.IntegerField(
                choices=[(40, "Seats 40"), (50, "Seats 50"), (60, "Seats 60")],
                default=40,
            ),
        )
    ]
