# Generated by Django 4.2.5 on 2023-09-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsmodel',
            old_name='teather',
            new_name='theater',
        ),
    ]
